"""Versioned browser-compute protocol for scalar-vacuum realizations."""

COMPUTE_PROTOCOL_SCHEMA = "physics-atlas.compute.v1"
SAMPLE_OPERATION = "scalar-vacuum.sample.v1"
SAMPLE_RESULT_SCHEMA = "physics-atlas.scalar-vacuum.sample.v2"
KERNEL_VERSION = "1.1.0"

DEFAULT_MAX_ELAPSED_MS = 45_000
HARD_MAX_ELAPSED_MS = 60_000
MEMORY_CACHE_MAX_ENTRIES = 6
MIN_MASS = 0.15
MAX_MASS = 1.60
MIN_CUTOFF_FRACTION = 0.25
MAX_CUTOFF_FRACTION = 0.85
MAX_SEED = 2_147_483_647
GRID_SIZE = 18
BOX_LENGTH = 12.0
TIME_SLICES = 17
TIME_HALF_WIDTH = 3.0
CORRELATION_SAMPLE_COUNT = 48

RESULT_SCHEMAS = {SAMPLE_OPERATION: SAMPLE_RESULT_SCHEMA}

ERROR_CODES = (
    "PROTOCOL_MISMATCH",
    "KERNEL_MISMATCH",
    "UNSUPPORTED_OPERATION",
    "INVALID_REQUEST",
    "INVALID_INPUT",
    "LIMIT_EXCEEDED",
    "CALCULATION_FAILED",
    "INVARIANT_FAILED",
    "RUNTIME_LOAD_FAILED",
    "CANCELLED",
    "SUPERSEDED",
    "TIMEOUT",
)
